notes_app/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"<Note {self.id}: {self.title}>"
    
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)

    def __repr__(self):
        return f"<User {self.id}: {self.username}>"

notes_app/app.py
from flask import Flask, request
from config import Config
from models import db
from notes.routes import notes_bp

app = Flask(__name__)
app.config.from_object(Config)
db.init_app(app)
app.register_blueprint(notes_bp)

@app.route('/acerca-de')
def about():
    return "Esto es una app de notas."

@app.route('/contacto', methods=['GET', 'POST'])
def contact():
    if request.method == 'POST':
        return "Formulario de contacto enviado.", 201
    return "Página de contacto"



# @app.route('/api/info') # Ruta creada para devolver información de la API en formato JSON
# def api_info():
#     data = {
#         "nombre": "App de Notas",
#         "version": "1.0.0",
#         "author": "Azfe",
#         "description": "API para la aplicación de notas"
#     }
#     return jsonify(data), 200

# if __name__ == '__main__':
#     app.run(debug=True) # Debug mode ON

notes_app/notes/routes.py
from flask import(         
    redirect, 
    render_template, 
    request, url_for,
    Blueprint,
    flash
)
from models import Note, db

notes_bp = Blueprint('notes', __name__)

@notes_bp.route('/')
# @app.route('/home')
def home():
    role = "admin"
    
    notes = Note.query.all()
    return render_template('home.html', role=role, notes=notes)

@notes_bp.route('/confirmacion', methods=['GET', 'POST'])
def confirmation():
    print(request)
    # return "Prueba de confirmación"
    title = request.args.get('title')
    content = request.args.get('content')
    return render_template('confirmation.html', title=title, content=content)

@notes_bp.route('/crear-nota', methods=['GET', 'POST'])
def create_note():
    if request.method == 'POST':
        title = request.form.get('title-note')
        content = request.form.get('content-note')
        
        note_db = Note(
            title=title,
            content=content
        )        
        db.session.add(note_db)
        db.session.commit()
        flash("Nota creada exitosamente.", "success")        
        print(f"Nota creada: {title} - {content}")
        return redirect(
            url_for('notes.home')
            # url_for('notes.confirmation', title=title, content=content)
        )
    return render_template('note_form.html')

@notes_bp.route('/editar-nota/<int:id>', methods=['GET', 'POST'])
def edit_note(id):
    note = Note.query.get_or_404(id)
    if request.method == 'POST':        
        title = request.form.get('title-note', 'Sin título')
        content = request.form.get('content-note', 'Sin contenido')
        
        note.title = title
        note.content = content
        
        db.session.commit()
        
        return redirect(url_for('notes.home'))        
    return render_template('edit_note.html', note=note)

@notes_bp.route('/eliminar-nota/<int:id>', methods=['POST'])
def delete_note(id):
    note = Note.query.get_or_404(id)
    if request.method == 'POST':
        db.session.delete(note)
        db.session.commit()
        return redirect(url_for('notes.home')) # esto genera un 302

notes_app/templates/confirmation.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmación de creación de nota</title>
</head>
<body>
    <h1>¡Nota creada exitosamente!</h1>
    <p><strong>Título:</strong> {{ title | default('Sin título', true) }}</p>
    <p><strong>Contenido:</strong> {{ content | e }}</p>
    <p>Serás redirigido a la página de inicio en 3 segundos...</p>

    <script>
        setTimeout(function() {
            window.location.href = "{{ url_for('notes.home') }}";
        }, 3000);
    </script>
</body>
</html>

notes_app/templates/edit_note.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear una nueva nota</title>
</head>
<body>
    <h1>Crear una nueva nota</h1>
    <form action="" method="POST">
        <!-- <label for="nota">Nota</label> -->
        <input type="text" name="title-note" id="title-note" placeholder="Título" value="{{ note.title }}"><br>
        <input type="text" name="content-note" id="content-note" placeholder="Contenido de la nota" value="{{ note.content }}"><br>

        <input type="submit" value="Guardar Nota">
    </form>
</body>
</html>

notes_app/templates/home.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página de inicio</title>
</head>
<body>
    <h1>Bienvenido a Flask Notes</h1>
    <h3>Usuario: {{ role }}</h3>
    {% if role == 'admin' %}
        <button>Eliminar</button><!-- Se muestre en el caso que usuario sea admin -->
    {% else %}
        <button>Solicitar eliminación</button>
    {% endif %}

    <hr>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul>
            {% for category, message in messages %}
                <li class="{{ category }}">{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    <ul>
        {% for note in notes %}
            <li>
                <h3>{{ note.title }} </h3>
                <p>
                    {{ note.content }} |
                    <a href="{{ url_for('notes.edit_note', id=note.id) }}">
                        ✏ Editar Nota
                    </a>
                    <form action="{{ url_for('notes.delete_note', id=note.id) }}" method="post">
                        <button type="submit">
                            🗑 Eliminar Nota
                        </button>
                    </form>
                    {#<!-- <button formaction="{{ url_for('notes.delete_note', id=note.id) }}" formmethod="post" type="submit">
                        🗑 Eliminar Nota
                    </button> -->#}
                </p>
                
            </li>
            {% else %}
            <h3>Aun no se han creado notas.</h3>
        {% endfor %}
    </ul>   

    <button type="button" onclick="window.location.href='{{ url_for('notes.create_note') }}'">
        Agregar una nueva nota
    </button>
    
</body>
</html>

notes_app/templates/note_form.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear una nueva nota</title>
</head>
<body>
    <h1>Crear una nueva nota</h1>
    <form action="" method="POST">
        <!-- <label for="nota">Nota</label> -->
        <input type="text" name="title-note" id="title-note" placeholder="Título" required><br>
        <input type="text" name="content-note" id="content-note" placeholder="Contenido de la nota" rows="4"><br>

        <input type="submit" value="Crear Nota">
    </form>
</body>
</html>

notes_app/templates/signin.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>Login de usuario</h1>
    <form action="" method="POST">
        <input type="text" name="username" id="username" placeholder="Nombre de usuario" required><br>
        <input type="password" name="password" id="password" placeholder="Contraseña" required><br>

        <input type="submit" value="Iniciar Sesión">    
</body>
</html>

notes_app/templates/signup.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
</head>
<body>
    <h1>Registro de usuario</h1>
    <form action="" method="POST">
        <input type="text" name="username" id="username" placeholder="Nombre de usuario" required><br>
        <input type="email" name="email" id="email" placeholder="Correo electrónico" required><br>
        <input type="password" name="password" id="password" placeholder="Contraseña" required><br>

        <input type="submit" value="Registrarse">    
</body>
</html>